### ISSUE TITLE
Wrapped IOS app stuck at white screen after re-installation.

### ISSUE THREAD

**Issue by lrmakode** [msintuneappsdk/intune-app-wrapping-tool-ios#63] opened 2021-05-28 10:00 UTC
**Describe the bug:**
App stuck at white screen on launch after re-installation. If the session is already authenticated(user is not asked for pin) then white screen appears.

**To Reproduce**
1. Install Wrapped Intune App.
2. Open and authenticate.
3. Unistall the App
4. ReInstall the app.(White screen appears on launch)

**Expected behavior:**
White screen should not appear. 

**Smartphone (please complete the following information):**
 - Device: iPhone-se,10,11,12. iPad-6thGen, 7thGen.
 - OS: iOS-13,14

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? Yes(14.4.1)
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Cocoa
- For pre-wrapping errors, does the app build without being wrapped? Yes
- For post-wrapping errors, does the app launch without being wrapped? Yes

**Additional context:**
The issue was observed after wrapping with the latest wrapping tool. previously we were using 12.8.0

**Comment by gastaffo** [comment] 2021-06-02 18:17
Hi @lrmakode. I was not able to reproduce this issue. Is your app a native Obj-C/Swift app? Can you provide a screen shot of the white screen you are seeing?

**Comment by lrmakode** [comment] 2021-06-03 08:37
Hi @gastaffo please find attached video in the following video issue is reproduced.  
https://user-images.githubusercontent.com/3403274/120613927-54081b80-c474-11eb-97c3-fa8a555804be.MP4

in the following video issue is not there as user is asked for authentication.
https://user-images.githubusercontent.com/3403274/120614317-b82adf80-c474-11eb-8a8d-a619f34a499a.MP4

**Comment by gastaffo** [comment] 2021-06-03 14:41
Hi @lrmakode. Ok looks like we aren't giving UI control back correctly. Can you send logs from the device? You can bring up the diagnostics console by going to the app in the settings panel Microsoft Intune -> Display Diagnostics Console.
 
Also does your app do any swizzling at start up?

**Comment by lrmakode** [comment] 2021-06-04 07:08
Hi @gastaffo please find logs attached. we are not using swizzling our iOS app.
[IntuneMAMDiagnosticFiles.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/6596415/IntuneMAMDiagnosticFiles.txt)

let me know if anything else is required, if you want I can send the logs for the case in which issue is not reproduced.

**Comment by gastaffo** [comment] 2021-06-04 17:38
Hi @lrmakode. Could you repro the issue again with verbose logging enabled? To enable verbose logging add the key "VerboseLoggingEnabled" to YES in the "IntuneMAMSettings" dictionary of the apps info.plist

**Comment by lrmakode** [comment] 2021-06-07 11:45
Hi @gastaffo please find attached verbose logs with verbose logging enabled.
**With Issue**
[IntuneMAMDiagnosticFiles_WithTheIssue.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/6606135/IntuneMAMDiagnosticFiles_WithTheIssue.txt)
**Without Issue**
[IntuneMAMDiagnosticFiles_WithoutTheIssue.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/6606138/IntuneMAMDiagnosticFiles_WithoutTheIssue.txt)

**Comment by gastaffo** [comment] 2021-06-07 16:13
Hi @lrmakode. We aren't noticing anything out of place in the logs. It would be best if we could start an support ticket. To do this go to https://endpoint.microsoft.com/#home "Troubleshooting + support" -> "Help and support" -> "Intune".

**Comment by gastaffo** [comment] 2021-06-07 16:20
Also another question, is the app linking to MSAL/ADAL before being wrapped?

**Comment by lrmakode** [comment] 2021-06-08 10:59
Hi @gastaffo, Thanks for the help we have raised issue at Microsoft support and to answer you question we are not using MSAL or ADAL in our app.

**Comment by iit2008047** [comment] 2021-11-19 14:52
I am also facing this issue ... Have you found RCA and the fix

**Comment by gastaffo** [comment] 2021-11-19 16:04
@iit2008047 Could you provide logs from your repro like above? With the verbose key enabled.

**Comment by iit2008047** [comment] 2021-11-22 08:15
To Reproduce
https://user-images.githubusercontent.com/76396/142637892-a658759e-d564-4224-875b-af521f94ded9.mp4

Expected behavior:
The wrapped app should open

pen
Screenshots and logs:
IntuneMAMDiagnosticFiles (1).txt

**Comment by iit2008047** [comment] 2021-11-24 20:35
[IntuneMAMDiagnosticFiles.1.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/files/7598581/IntuneMAMDiagnosticFiles.1.txt)
@gastaffo here is the log

**Comment by gastaffo** [comment] 2021-12-10 17:21
Closing as is solved in https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/68

**Closed by gastaffo** 2021-12-10 17:21 UTC
