### ISSUE TITLE
Wrapping fails on an app that already has ADAL.

### ISSUE THREAD

**Issue by consoleboy** [msintuneappsdk/intune-app-wrapping-tool-ios#19] opened 2019-04-15 16:42 UTC
Wrapping fails when we try to inject an App that already has the ADAL library.
Is the iOS wrapping tool only for apps that do not have ADAL already installed?

Thank you.

Warren
![imgo-1](https://user-images.githubusercontent.com/28855676/56150183-e9ce4d00-5f73-11e9-94cd-fd3a98a8af1c.jpg)

**Comment by Kyle-Reis** [comment] 2019-04-15 16:52
Hey @consoleboy, This scenario should be supported in our latest release (10.0.1). Version 10.0.1 also makes some new parameters available that allow you to specify AAD settings to enable SSO between the SDK and your app. Also, I noticed from your screenshot that you have Xcode 10.2 installed. Was your app built with 10.2?

**Comment by consoleboy** [comment] 2019-04-15 22:47
Thanks will give it a spin. Is 10.0.1 beta or public? Thx

**Comment by consoleboy** [comment] 2019-04-16 20:19
Thank you, I tried downloading the dmg i get the following error. My colleague got the same on his macbook pro as well.. 
![Screen Shot 2019-04-16 at 3 17 59 PM](https://user-images.githubusercontent.com/28855676/56241222-f083bf80-605a-11e9-8cc0-7dd93fd773e2.png)

**Comment by Kyle-Reis** [comment] 2019-04-16 20:59
Hey @consoleboy, 10.0.1 is public. How are you downloading the DMG? I just tried it and was able to mount it without any issues. The reason for my asking if your app is built with Xcode 10.2 is that the current version of our SDK/wrapper don't yet support Swift apps built with 10.2. We're working to get this supported ASAP. Is any part of your app written in Swift?

**Comment by consoleboy** [comment] 2019-04-17 19:20
Thanks Kyle, My colleague and I get the same error when we try to download the dmg and mount it using OSX 10.14.4 (Mojave).

**Comment by consoleboy** [comment] 2019-04-17 19:25
Tried running disk utility on the DMG and I get a permission denied issue.
![Screen Shot 2019-04-17 at 2 24 10 PM]
![Screen Shot 2019-04-17 at 2 24 10 PM](https://user-images.githubusercontent.com/28855676/56315175-ab27c680-611c-11e9-9121-1737d520997d.png)

**Comment by Kyle-Reis** [comment] 2019-04-18 14:54
Hey @consoleboy. I'm not sure what might be happening on your system and your colleague's, but I'm running the same version of MacOS and am able to successfully mount. Did you each download the DMG directly from our GitHub repo, or did you share the file you downloaded with your colleague? I'm wondering if the download was somehow corrupted. Could you try rebooting your system (to get rid of those "ghost" images) and re-downloading? If that doesn't work, could you share the exact steps used to download the file?

**Comment by consoleboy** [comment] 2019-04-23 14:08
Hi we both downloaded the DMG from the github repo.
We have trashed our browser cache and redownloaded.

1. We go to https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios
2. We click on the link to https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/blob/master/Microsoft%20Intune%20Application%20Restrictions%20Packager%20for%20iOS.dmg
3. We try to open the DMG
4. DMG cant be mounted.

**Comment by Kyle-Reis** [comment] 2019-05-14 13:27
Hey @consoleboy were you able to get this resolved? It seems like it could be caused by some sort of administrative restriction in your organization, as we haven't had anyone else report this...

**Comment by Kyle-Reis** [comment] 2019-05-30 12:59
Hey @consoleboy, just checking in again before closing out this issue on whether you were able to get the DMG mounting problem resolved.

**Comment by Kyle-Reis** [comment] 2019-06-07 22:17
Closing out this issue due to inactivity. Please feel free to reopen if you’re still experiencing the mounting issue

**Closed by Kyle-Reis** 2019-06-07 22:17 UTC
