### ISSUE TITLE
InTune wrapped apps aren't supporting opening with url

### ISSUE THREAD

**Issue by Mason11987** [msintuneappsdk/intune-app-wrapping-tool-ios#46] opened 2020-09-15 21:47 UTC
I have an InTune wrapped app that is set up to open PDFs:

	<dict>
		<key>CFBundleTypeName</key>
		<string>PDF</string>
		<key>LSHandlerRank</key>
		<string>Alternate</string>
		<key>LSItemContentTypes</key>
		<array>
			<string>com.adobe.pdf</string>
		</array>
	</dict>

It works perfectly:

1. If I run it on the simulator.  Whether the open-in loads the app cold, or just activates it.
2. If I run it on device, not wrapped. Whether the open-in loads the app cold, or just activates it.
3. If I run it on a device, wrapped.  But only if the app is already opened. If it has to cold-open it, it can't find the file.

I suspect there's something going on regarding what app actually receives the file and where that's located.

Any advice on this, how the app wrapping works, and how this iOS function works with wrapped apps?

Or is this a bug?

**Comment by Kyle-Reis** [comment] 2020-12-07 20:37
Hi @Mason11987, we have a potential fix for this issue in code review now. Will update you once it's available.

**Comment by Kyle-Reis** [comment] 2021-01-26 00:26
Hey @Mason11987, could you try out our [latest release](https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/releases/latest) (version 14.1.0)?

**Comment by Mason11987** [comment] 2021-01-26 13:39
Will do, will report back on here when we're able to  validate if that fixed it.

**Comment by Kyle-Reis** [comment] 2021-02-16 16:17
Hi @Mason11987, were you able to check if the issue is resolved with the latest release?

**Comment by Mason11987** [comment] 2021-02-16 17:02
Haven't yet, this isn't our highest priority item right now.  Thanks

**Comment by Mason11987** [comment] 2021-02-22 18:28
> Hi @Mason11987, were you able to check if the issue is resolved with the latest release?

Was able to check it today (had to rewrap due to 14.5 beta breaking things) and we're still facing the same issue.

If there's anything else I can offer besides my initial bug let me know.  Thanks!

**Comment by ShruthiAchutha** [comment] 2024-02-23 18:25
Closing stale issues. Please reopen if you still need help with this.

**Closed by ShruthiAchutha** 2024-02-23 18:25 UTC
