### ISSUE TITLE
Issues with Intune SSO post-wrapping with tool

### ISSUE THREAD

**Issue by paulpopiel** [msintuneappsdk/intune-app-wrapping-tool-ios#48] opened 2020-12-18 06:45 UTC
We have an iOS application that has been setup with MSAL. Our MSAL login + Azure AD configuration works standalone with no problems.

However once we apply the iOS Intune wrapping tool as per:
https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios

We run into the following issues.

1) If we apply the wrapping using the standard command using the default ADAL settings (i.e. omitting the -aa, -ac, -ar paramaters), then we face the following error:

![file](https://user-images.githubusercontent.com/8855763/102583080-e888f680-413e-11eb-82ed-2bca80cf300b.jpeg)

As we understanding it, the app id referenced in this error (i.e. 6c7e8096-f593-4d72-807f-a5f86dcc9c77) is the built-in default Intune MAM app registration. However we see no way of actually gaining access or configuring this in anyway to set redirect/reply urls.

2) If we apply the following parameters:
-aa "https://login.microsoftonline.com/[tenant-id]"
-ac "[client-id]"
-ar “msauth.[bundle-id]://auth”

(as per our existing MSAL configuration, which works standalone)

we then get the following error:

<img width="327" alt="Screen Shot 2020-12-18 at 2 40 40 pm" src="https://user-images.githubusercontent.com/8855763/102583218-40276200-413f-11eb-80f4-eeb837ebb2d9.png">

Any guidance as to what we may be missing or doing wrong would be greatly appreciated.

**Comment by Kyle-Reis** [comment] 2020-12-18 16:41
Hi @paulpopiel, it sounds like you have source code access for this app? is there a technical reason for the decision to wrap the app instead of integrating the Intune SDK?

**Comment by paulpopiel** [comment] 2020-12-19 06:31
Hi @Kyle-Reis 
We are using Flutter and there is no Intune SDK pub package for it as far as we are aware.

**Comment by Kyle-Reis** [comment] 2020-12-19 13:17
Hi @paulpopiel, could you try removing the quotes around the values specified for custom AAD settings in command line? Depending on how the quotes were entered, they may be getting treated as part of the setting value and leading to issues

**Comment by paulpopiel** [comment] 2020-12-20 05:07
I have lodged a service request with our deployment team to try this and will report back later. Fingers crossed its that simple.

**Comment by paulpopiel** [comment] 2020-12-21 04:14
Hi @Kyle-Reis 
We tried a few different things and ultimately the following setup got past the MSALErrorDomain error:

```
-aa login.microsoftonline.com/[tenant-id]
-ac [client-id]
-ar msauth.[bundle-id]://auth
```

However we are now presented with the following error:

![image002](https://user-images.githubusercontent.com/8855763/102738622-a43b6780-4385-11eb-8050-349941762a62.png)

We understand this is a standard Intune error:

![Screen Shot 2020-12-21 at 11 53 58 am](https://user-images.githubusercontent.com/8855763/102738647-b917fb00-4385-11eb-9cdd-da93acb2353e.png)

Our Intune team is looking into the remediation, however in the meantime any pointers or assistance to guide us in the right direction would also be much appreciated.
NOTE: this is the UAT version of the app. Is it recommended to turn off or bypass the Intune auth (or the app protection policies) for UAT versions?

**Comment by Kyle-Reis** [comment] 2020-12-21 15:13
Hi @paulpopiel, this error is shown when the user is not targeted with app protection policies for the app. Does the UAT version of the app have a different bundle ID from the production version? Apps are targeted for policy based on bundle ID, so your team may need add the UAT bundle ID to the list of targeted apps in addition to the production version.

**Comment by paulpopiel** [comment] 2020-12-22 04:18
Hi @Kyle-Reis , we have confirmed that both the user and the policy exist. 
However one thing I did notice is that the add is created through the following process: 
https://docs.microsoft.com/en-us/mem/intune/apps/lob-apps-ios
Noting that the bundle id is never manually specified (although it does show up correctly as per the uploaded IPA subsequently in the apps list in Intune).
When editing the policy, when adding a custom app (LOB app) - searching by the bundle id doesnt show any results, but the app does appear when searching by the name assigned during the creation above.

Which makes me wonder, is the policy potentially tied to the IPA file that is uploaded, and not just to the associated bundle id? 
Note that we get the error during side-load testing (i.e. before the wrapped IPA is actually updated/re-uploaded in Intune).

**Comment by Kyle-Reis** [comment] 2020-12-22 17:08
Hey @paulpopiel, when IPAs are uploaded for distribution via Company Portal, the app name will appear in app protection policy targeting UI as you've mentioned. Under the hood though, all targeting is based on bundle ID. Endpoint Manager is able to get the bundle ID for the app from the Info.plist inside of the uploaded .ipa file. 

Does the UAT version of this app use the same bundle ID as the production version? If not, the bundle ID may need to be added to the list of targeted apps in the policy settings.

**Comment by paulpopiel** [comment] 2020-12-24 02:21
Hi @Kyle-Reis, yes the UAT version has a different bundle id, however both it and the production version have both been added as separate apps in Intune. Likewise each has its own policy created, each targeting the respective version (i.e. a production policy as well as a uat policy).

**Comment by Kyle-Reis** [comment] 2020-12-28 16:54
Hi @paulpopiel, is the UAT policy also targeted to a user group which contains the account you are using to test the app?

**Comment by paulpopiel** [comment] 2020-12-29 16:57
Hi @Kyle-Reis 
Yes we have also checked this and confirmed that this is setup correctly.
P.s. thank you for your time and patience in trying to help us identify the issue.

**Comment by Kyle-Reis** [comment] 2020-12-29 17:02
@paulpopiel, No problem! :) could you check if the following settings on the app protection policy are configured differently? If so could you share what they are set to?

![image](https://user-images.githubusercontent.com/7443106/103300780-b80e4b80-49cd-11eb-8245-a29643ef2414.png)

**Comment by paulpopiel** [comment] 2020-12-29 17:11
<img width="612" alt="Screen Shot 2020-12-30 at 1 09 07 am" src="https://user-images.githubusercontent.com/8855763/103301235-e32f8400-4a3b-11eb-87da-118c1055161e.png">

**Comment by paulpopiel** [comment] 2020-12-29 17:49
@Kyle-Reis - side question related to the original error we are facing in production, i.e. the following error where the IPA was wrapped with default parameters (without the use of -aa, -ac, -ar)

![file](https://user-images.githubusercontent.com/8855763/103303417-e2e5b780-4a40-11eb-814a-e886e9ca4b73.jpeg)

We have more details from the AAD monitoring sign in logs related to this error:

![Screen Shot 2020-12-17 at 12 13 46 pm](https://user-images.githubusercontent.com/8855763/103303474-0446a380-4a41-11eb-8250-73cd2e3074bf.png)

any ideas as to what could be causing this?
Some extra context: everything was working fine for a number of months (8-9 months) and the number of users started to ramp up (i.e. not all at same time) reporting the interactive prompt with the error above. 
Although now we suspect that this error was always happening, just that it was also happening silently and subsequently not blocking the app from proceeding to its own MSAL auth flow.

**Comment by paulpopiel** [comment] 2020-12-29 18:03
Just found the following: https://docs.microsoft.com/en-us/troubleshoot/mem/intune/error-query-intune-data-warehouse
Could this be related/similar in any way? (Not sure if there is any link between Intune Data Warehouse and the built-in "Intune Applications" app referenced above)

**Comment by paulpopiel** [comment] 2020-12-29 18:16
@Kyle-Reis 
Apologies for the spam, but also found this:
https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/905

Which seems to be the exact same error we faced.

I have inspected the Info.plist file in the wrapped IPA and it seems to be encrypted/scrambled so its hard to see if the `IntuneMAMSettings` dictionary is being set and if so if those entries are being set correctly if the wrapping tool parameters are used, i.e.

```
-aa login.microsoftonline.com/[tenant-id]
-ac [client-id]
-ar msauth.[bundle-id]://auth
```

All I can see in the Info.plist is the following:
`ADALAuthority\ADALClientId_AutoEnrollOnLaunch_ADALRedirectUri_`

**Comment by paulpopiel** [comment] 2020-12-29 19:02
@Kyle-Reis 
One last thing:
https://docs.microsoft.com/en-gb/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional

I'm not sure if we have done the above (would need to check with our AAD team), but could this potentially cause the "App Not Set Up: This app has not been set up for you to use. Contact your IT administrator for help" error if it hasn't been set up?

**Comment by Kyle-Reis** [comment] 2020-12-29 19:59
Hi @paulpopiel, the latest version of the app wrapper does not inject ADAL when the app already links to MSAL. With MSAL, using custom client ID and redirect URI for Intune enrollment is required due to strict redirect URI format enforced by MSAL which is based on individual app's bundle ID.

If you the above steps have not been followed to give the app access to the Intune MAM service, that is likely the root cause of the "Account Not Setup" error.

**Comment by paulpopiel** [comment] 2020-12-30 02:18
Hi @Kyle-Reis 

> the latest version of the app wrapper does not inject ADAL when the app already links to MSAL. With MSAL, using custom client ID and redirect URI for Intune enrollment is required due to strict redirect URI format enforced by MSAL which is based on individual app's bundle ID.

Thank you very much for that clarification. That confirm the use of the -aa, -ac, -ar parameters is required and we will continue down that path.

> If the above steps have not been followed to give the app access to the Intune MAM service, that is likely the root cause of the "Account Not Setup" error.

Fingers crossed. I will raise a Service Request with our AAD team to check and add (if missing) the above access and report back.

**Comment by paulpopiel** [comment] 2020-12-30 03:37
We have confirmed the Intune MAM service permissions are NOT present in the AAD app registration.

Have raised a service request to have this addressed and will report whether this solves the 'Account not setup' error post-wrapping.

Thanks again.

**Comment by paulpopiel** [comment] 2020-12-30 03:44
Oh one more thing @Kyle-Reis 
when you say:

> the latest version of the app wrapper does not inject ADAL when the app already links to MSAL.

Out of curiosity - does that mean it used to inject ADAL, and if so when was this change released?

**Comment by paulpopiel** [comment] 2020-12-31 06:13
Hi @Kyle-Reis 
We are still facing the "Account Not Setup" error on app open, even with the Intune MAM service API permission setup in AAD.

Interestingly I setup a new device with Intune Company Portal and when I ran the app for the first time it failed on app open with an "Unexpected Failure. Contact your IT administrator for help" error. 
I then opened an install and ran an existing company app (that use ADAL), which opened and logged in as expected. 

I then went back to our app and re-opened it, and was now faced with the "Account Not Setup" error. 

So I guess the question is why did the app, when no existing cached token existed, fail with the "Unexpected Failure" error? are we missing something that this sheds like on? (couldnt find any more information or logs as to more details on this unexpected failure). 
Secondly - if there is a cached token, but from an ADAL setup app - does this cause any issues that may be related to the "account not setup" error?

Any thoughts/ideas?

**Comment by paulpopiel** [comment] 2020-12-31 10:08
Further context - existing apps have been setup using **ADAL**, with Intune SDK either integrated or wrapped with **default intune values** for ClientID and redirectURI (i.e. IntuneMAMSetting entries omitted)

**Comment by paulpopiel** [comment] 2020-12-31 10:57
Another FYI - we are using the following Flutter dependancy for our in-app MSAL:
https://github.com/gbwisx/msal_mobile

Looks like that uses MSAL v1.0.5 under the hood for iOS.

**Comment by paulpopiel** [comment] 2021-01-04 10:12
@Kyle-Reis - So we applied the Intune MAM API permission to AAD. There was no impact initially, although it seems that it took a few hours (24+ roughly) for those permissions to propagate through. 
Interestingly though, it doesnt seem to be working for all our users.

Specifically the policy for the UAT version of the app has two groups assigned:
- Our application team UAT group
- The India based service teams own internal testing group

All our users in the application team have managed to install the app and the policies are detected and login works. However users from our service team are still getting the 'Account Not Setup' error when checking for policy.

Initially I thought it may have something to do with the Intune groups, however we had them remove me from the application UAT group and added to theirs, and I still managed to login fine without the error.

We are a bit baffled now as to what may be causing their users to have issues and not ours. 
The only real differentiator that we have identified is that we are all Australia based, and they are in India... although I dont see how that can have any effect.

**Comment by Kyle-Reis** [comment] 2021-01-04 16:30
Hi @paulpopiel, it sounds like this may be a matter of the added API permission not fully propagating to all servers. Is the team in India still seeing the issue?

**Comment by paulpopiel** [comment] 2021-01-05 05:57
Hi @Kyle-Reis , they are still facing the same error this morning. Is it common for AAD API permissions to take this long (days) to propagate? and for there to be such a differentiation between regions?

**Comment by Kyle-Reis** [comment] 2021-01-05 14:45
@paulpopiel, it shouldn't take that long. Do the accounts that the India team is testing with have an Intune license assigned to them? If not, MAM enrollment would fail, which would also produce this error.

**Comment by paulpopiel** [comment] 2021-01-05 16:19
@Kyle-Reis I will check on this tomorrow with the Intune team. However, these users have had no issues with the pre-existing ADAL based apps that have been deployed. Unless there is some key difference in relation to this with ADAL vs MSAL? (excuse my ignorance on this subject)

**Comment by paulpopiel** [comment] 2021-01-06 16:10
@Kyle-Reis All users by default have the Office 365 E3 license assigned to them with Intune enabled, so thats not the cause of the India team members still getting the 'Account Not Set Up' error.

**Comment by paulpopiel** [comment] 2021-01-08 06:20
@Kyle-Reis - we decided to roll the dice and went ahead with a production deployment with the current setup, hoping it was an isolated case with the 'Account Not Set Up' issue just with our India team members.

We have had reports of users who previously had the original 'reply URL' error having solved that problem, but we are unfortunately starting to get a small handful of reports from users also experiencing the new 'Account Not Set Up' error.

What other scenarios could potentially cause this 'Account Not Set Up' error? 
Is there any potential interaction with SSO with previous enrollments/tokens from other Apps setup with ADAL that could somehow trigger this? we are grasping at straws at this stage.

**Comment by paulpopiel** [comment] 2021-01-08 08:47
@Kyle-Reis - another (separate although potentially related) issue:
On a fresh device (out of the box setup, with only Company Portal and Authenticator installed. i.e no existing application enrolments or tokens.

When we run the app we get:
![Image from iOS](https://user-images.githubusercontent.com/8855763/103993661-eca1b480-51d0-11eb-915c-e83319cb5c20.png)

Has this got anything to do with:

AutoEnrollOnLaunch | Boolean | Specifies whether the app should attempt to automatically enroll on launch if an existing managed identity is detected and it has not yet done so. Defaults to NO.Notes: If no managed identity is found or no valid token for the identity is available in the MSAL cache, the enrollment attempt will silently fail without prompting for credentials, unless the app has also set MAMPolicyRequired to YES.
-- | -- | --

**Comment by paulpopiel** [comment] 2021-01-08 08:55
@Kyle-Reis - apologies, spamming again.

Following on from the fresh device scenario: 

Interestingly when we then install and login to a different company app, and then come back to ours - we no longer get the above 'unexpected failure', but now get the 'Account Not Set Up' error. 

So not sure how the majority of our user base is actually not getting this error in production. Is there some sort of interaction with previous enrolments/tokens, either coming from previous version or from other apps....

Hope this leads to potentially shedding some further light and maybe some new ideas as to what the issue may be?

**Comment by Kyle-Reis** [comment] 2021-01-08 15:22
Hi @paulpopiel, could you follow [these instructions](https://docs.microsoft.com/mem/intune/developer/app-wrapper-prepare-ios#collecting-logs-for-your-wrapped-applications-from-the-device) to collect Intune logs for the app and send them to me along with a copy of the wrapped app's Info.plist at KyleReis@microsoft.com? It sounds like there may be a problem with the AAD settings configured which is leading to the "Unexpected Failure". However, when another one of your apps app has already acquired a token, we're able to access the MAM service silently without prompting the user for credentials, but there is some other problem which is leading to the "Account Not Setup" error.

**Comment by paulpopiel** [comment] 2021-01-09 07:04
Hi @Kyle-Reis  - email sent with the requested files. Thank you very much for the assistance.

**Comment by Kyle-Reis** [comment] 2021-01-12 15:28
Closing out this issue as root cause was determined (missing "https://" in the authority URI).

**Closed by Kyle-Reis** 2021-01-12 15:28 UTC

**Comment by OmarHassan25** [comment] 2021-12-17 06:20
> Closing out this issue as root cause was determined (missing "https://" in the authority URI).

@Kyle-Reis i have the sane issue with ny wrapped application, domainerrorcode - 50000, my authority uri contains the https part,..
. Could you please help what may cause the issue?

**Comment by OmarHassan25** [comment] 2021-12-17 06:21
> We have an iOS application that has been setup with MSAL. Our MSAL login + Azure AD configuration works standalone with no problems.
> 
> However once we apply the iOS Intune wrapping tool as per: https://docs.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios
> 
> We run into the following issues.
> 
> 1. If we apply the wrapping using the standard command using the default ADAL settings (i.e. omitting the -aa, -ac, -ar paramaters), then we face the following error:
> 
> ![file](https://user-images.githubusercontent.com/8855763/102583080-e888f680-413e-11eb-82ed-2bca80cf300b.jpeg)
> 
> As we understanding it, the app id referenced in this error (i.e. 6c7e8096-f593-4d72-807f-a5f86dcc9c77) is the built-in default Intune MAM app registration. However we see no way of actually gaining access or configuring this in anyway to set redirect/reply urls.
> 
> 2. If we apply the following parameters:
>    -aa "[https://login.microsoftonline.com/[tenant-id]](https://login.microsoftonline.com/%5Btenant-id%5D)"
>    -ac "[client-id]"
>    -ar “msauth.[bundle-id]://auth”
> 
> (as per our existing MSAL configuration, which works standalone)
> 
> we then get the following error:
> 
> <img alt="Screen Shot 2020-12-18 at 2 40 40 pm" width="327" src="https://user-images.githubusercontent.com/8855763/102583218-40276200-413f-11eb-80f4-eeb837ebb2d9.png">
> 
> Any guidance as to what we may be missing or doing wrong would be greatly appreciated.

@paulpopiel i have the msaldomainerror 50000, could you please advise how you fixed it?

**Comment by basav22** [comment] 2025-02-21 07:33
@Kyle-Reis - Are these input params (client id, tenant id) needed to android app (apk) which is Intune Wrapped ? 
OR is it needed? since I checked online docs - it does not specify anything.
It would be great if you can help with param names to be passed in command 

Thanks in advance.

**Comment by manupa-ms** [comment] 2025-02-24 07:42
@basav22 , yes these are required parameters to be passed when wrapping the app. Here is a list of all command line parameters available and it also highlights the ones which are optional:
https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#command-line-parameters

The requirement is also highlighted here: https://learn.microsoft.com/en-us/mem/intune/developer/app-wrapper-prepare-ios#register-your-app-with-microsoft-entra-id

**Comment by basav22** [comment] 2025-02-24 14:40
Thanks for replying. I am checking for Android app. Not iOS app. 
If for Android is necessary, how to do so?
I am getting error - Failed to login for my android app

**Comment by manupa-ms** [comment] 2025-02-27 08:23
@basav22 , in case of Android app wrapping tool, these parameters are not required as App registration is not mandatory. If you're seeing errors after using the tool, please raise a new issue under [Android app wrapping repo](https://github.com/microsoftconnect/intune-app-wrapping-tool-android/issues) using the template provided so we can take a look in detail.

**Comment by basav22** [comment] 2025-02-27 15:48
Thanks @manupa-ms . Anyways - We have integrated intunes android SDK and successfully deployed
