### ISSUE TITLE
Ipa framework side effect in 11.2.0 version

### ISSUE THREAD

**Issue by daordonez11** [msintuneappsdk/intune-app-wrapping-tool-ios#30] opened 2019-09-23 16:56 UTC
**Describe the bug:**
Running the wrapping command with the 11.0.3 version works but fails with version 11.2.0

**To Reproduce**
Execute wrapping command with 11.0.3 in our test Ipa result:
The application was successfully packaged
Execute Wrapping command with version 11.2.0 in the same Ipa, result:
The app's Frameworks directory could not be signed. This may be because it contains files whose format was unrecognized, invalid, or unsuitable.
Cause of the error to be provided for investigation:Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign exited with an error." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign exited with an error.}

**Expected behavior:**
Running the command with the same parameters in 2 different version should work in the same way for both.
**Screenshots and logs:**
![image](https://user-images.githubusercontent.com/13544910/65445874-c8ae3a00-ddf8-11e9-983e-70c5c5b2304c.png)
![image](https://user-images.githubusercontent.com/13544910/65445912-d9f74680-ddf8-11e9-9050-3327aec0d211.png)
Input params:
![image](https://user-images.githubusercontent.com/13544910/65446027-162aa700-ddf9-11e9-8e16-816a6ea8e0dd.png)

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
11.0.3 and 11.2.0

**Comment by Kyle-Reis** [comment] 2019-09-23 18:26
Hey @daordonez11, I believe I've identified the root cause of this issue.  Just to confirm, could you verify that you are specifying a SHA-1 certificate hash and getting the warning about it being deprecated? Could you also confirm that if you specify the cert name instead, it works?

**Comment by Kyle-Reis** [comment] 2019-10-08 13:41
Hey @daordonez11, just checking in again to see if specifying the certificate name worked for you?

**Comment by rliljest** [comment] 2019-10-09 14:22
I have the same issue with the latest `12.0.12` version. If I specify the hash I get the deprecation warning and the above error, but if I specify the cert name instead I just get the error.

**Comment by Kyle-Reis** [comment] 2019-10-09 15:59
Hey @daordonez11 and @rliljest, could either of you list out the file extension types that are contained within the "Frameworks" directory of your app bundle?

**Comment by Kyle-Reis** [comment] 2019-10-09 16:27
Actually, if either of you could share the complete contents of the Frameworks directory, that would be quite helpful

**Comment by rliljest** [comment] 2019-10-09 16:57
We have several IPAs that show the same issue, and one of them does not even have a `Frameworks` directory

**Comment by Kyle-Reis** [comment] 2019-10-09 17:28
Hey @rliljest, were the IPAs you are attempting to wrap built with Xcode 11?

**Comment by rliljest** [comment] 2019-10-09 18:17
Built with Xcode 11, but using the legacy build system

**Comment by Kyle-Reis** [comment] 2019-10-09 19:11
What do you mean by legacy build system? Does the machine you are wrapping with have Xcode 11 installed along with command line tools as well?

**Comment by rliljest** [comment] 2019-10-09 19:42
Yes, built using Xcode 11 using the iOS 13 SDK. The legacy build system might not be relevant. 
![legacy_build_system](https://user-images.githubusercontent.com/13106809/66514573-0c649d00-eaa3-11e9-8743-a847a790d2ef.png)

**Comment by Kyle-Reis** [comment] 2019-10-09 20:17
Are you wrapping on the same machine with Xcode 11 installed?

**Comment by rliljest** [comment] 2019-10-09 20:36
Different machine, but both are using Xcode 11

**Comment by rliljest** [comment] 2019-10-16 13:47
@Kyle-Reis I found out what the issue is with this error.

We have two distribution certificates with the same name: one for enterprise distribution (which we will wrap with the intune app wrapping tool) and one for app store distribution. Our development machines have both certificates installed.

Regardless of if we provide the (deprecated) cert hash or the certificate name, the error is the same. If I remove the app store certificate from my keychain, then the wrapping tool works without issue. I have verified that the provisioning profile specified is only associated with the enterprise cert (per our discussion on https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios/issues/29).

So it looks like at some point, the duplicate names are causing confusion. Since we need to be able to work on public and enterprise builds, removing the app store cert from our machines is not a viable solution.

**Comment by Kyle-Reis** [comment] 2019-10-24 14:15
Hey @rliljest, just wanted to let you know we have a potential fix for this issue in review now.

**Comment by rliljest** [comment] 2019-11-14 14:12
@Kyle-Reis Any estimate on when the fix would be available?

**Comment by Kyle-Reis** [comment] 2019-11-26 14:59
Hey @rliljest, this fix is NOT included in yesterday's update. It should be in the next update. ETA is sometime in December.

**Comment by daordonez11** [comment] 2020-01-08 22:43
Hello, Kyle! Sorry I hadn't read my Github notifications, do you still require anything from my side?

**Comment by Kyle-Reis** [comment] 2020-01-08 22:50
@daordonez11 Nope! We’re working on releasing the fix. Should be out soon!

**Comment by rliljest** [comment] 2020-01-15 14:41
Saw the 12.2.0 update and verified it fixed the issue I was having. Thanks a lot @Kyle-Reis and team!

**Comment by Kyle-Reis** [comment] 2020-01-15 16:17
No problem 🙂 @daordonez11 just an FUI that this issue is foxed in the latest release (12.2.0)

**Closed by Kyle-Reis** 2020-01-15 16:17 UTC

**Comment by daordonez11** [comment] 2020-02-04 20:22
Hey @Kyle-Reis  today I downloaded 11.2.0 and tried to test it but in my mac it said that the tool was corrupted and I wasn't able to test it

**Comment by kiranprakash912** [comment] 2020-12-22 07:29
Hi Need urgent help! I am seeing the same error though i am running the latest version to wrap the LOB app


Warning: Unable to verify system settings for certificate revocation checks. If you would like to enforce certificate revocation checks, run the following commands - 'defaults write com.apple.security.revocation CRLStyle BestAttempt' and 'defaults write com.apple.security.revocation OCSPStyle BestAttempt'

**Execution of defaults failed with error: Error Domain=IntuneAppPackager Code=1 "/usr/bin/defaults exited with an error." UserInfo={NSLocalizedDescription=/usr/bin/defaults exited with an error.}.**

Packager Version: 14.0.0, Packager Build: 2011.9, App Build: 1.1.0, Concatenated Build: 2026.10.0

The app's Frameworks directory could not be signed. This may be because it contains files whose format was unrecognized, invalid, or unsuitable.

Cause of the error to be provided for investigation:Error Domain=IntuneAppPackager Code=1 "/usr/bin/codesign exited with an error." UserInfo={Error Description=SignFrameworksError, NSLocalizedDescription=/usr/bin/codesign exited with an error.}

**Comment by OmarHassan25** [comment] 2021-12-16 16:25
Guys, i am having the same error, I am using the latest wrapping tool build, any help?

**Comment by Coruscate5** [comment] 2024-09-18 21:05
I fixed this issue by just adding the commands as they requested in the warning: `defaults write com.apple.security.revocation CRLStyle BestAttempt` and `defaults write com.apple.security.revocation OCSPStyle BestAttempt`

The cert revocation mechanism expects to be able to use ... something .. for the defaults program. By default the style is not BestAttempt
