### ISSUE TITLE
Unable to open/pass information to MAM policy exempt app

### ISSUE THREAD

**Issue by rooneytx** [msintuneappsdk/intune-app-wrapping-tool-ios#57] opened 2021-04-02 15:58 UTC
We have the iOS MAM setting “Send org data to other apps” set to Policy Managed apps. The issue is that any of the non-managed apps we include the “Select apps to Exempt” section are not launching or if launching are not populated with info we are passing to them.

Example: We are trying to pass information from the MAM app to the iOS native email app as well as to the native text message app. We have used the Native controller calls which we have been told are not support (confused as why not). We have used the cordova windon.open() and linking.openURL() calls and still we are not able to pass information to the exempt apps. 

In some cases the exempt app will open but none of the passed text is populated in the app. In other cases the app will not open and we don’t receive any error message or the MAM notification indication this action is blocked.  We have pulled the MAM app diagnostics logs and they aren’t provide any beneficial information to trouble shoot the issue. 

Would like to understand what calls are required to have this work correctly. As this is currently delaying the deployment of our application.

Not sure if this is related to issue #45.

Regards, 

Rooney

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 

**Smartphone (please complete the following information):**

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by Kyle-Reis** [comment] 2021-04-05 22:03
Hi @rooneytx - this issue is the same as issues [126](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/126) and [127](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/127) in our SDK repository. As such I will close out this issue as well as 127 so that it can be tracked in a single place. At it's core, the problem is that the apps are attempting to use built-in view controllers to share data to the native Messages and Mail app when outgoing share policy is restricted to policy-managed apps with exemptions specified for "mailto" and "sms" URL schemes. Although the actual cross-platform code written is using the APIs you mentioned above to open URLs with those schemes, these calls appear to be getting translated into in-app view controller presentations at the native layer, and since the scheme exemption list currently applies only to URLs, these view controllers are blocked from being presented or data is blocked from being transferred to them. We are considering making a change to allow these VCs to be used when "mailto" or "sms" have been added to the URL scheme exemption list, but there are some concerns about potential inconsistencies this may introduce with regard to file attachments. I will post an update to issue [126](https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/126) once the team has reached a decision. In the meantime, I would investigate if there's any way to work around or disable the apparent substitution of mailto and sms links with these native view controllers at the Cordova level.

**Closed by Kyle-Reis** 2021-04-05 22:03 UTC

**Comment by Kyle-Reis** [comment] 2021-04-15 18:27
@rooneytx - does your application's config.xml have access entries specified for "sms:*" and "mailto:*" with the launch-external attribute configured to "yes", as mentioned [here](https://cordova.apache.org/docs/en/4.0.0/guide/appdev/whitelist/#external-application-whitelist)? If not, could you give this a try?

**Comment by rooneytx** [comment] 2021-04-22 17:47
Hi,

We already set the Launch-external to yes. From the config file.

 <access launch-external="yes" origin="sms:*" />
    <access launch-external="yes" origin="mailto:*" />

Rooney

??

________________________________
